City List Template
AliMD/flight-finder pull request #24
Opened 2022-11-24 11:39 UTC by MM25Zamanian

2022-11-25 15:47 UTC, AliMD commented on pwa/src/component/job-item.ts
> +        margin-left: 0.5em;
خب وقتی گفتی slot='start' اینم بکن margin-start

2022-11-25 15:51 UTC, AliMD requested changes

2022-11-25 15:51 UTC, AliMD commented on pwa/src/component/job-item.ts
> +        margin-right: 0.5em;
end

2022-11-25 15:51 UTC, AliMD commented on pwa/src/component/job-item.ts
> +        margin-left: 0.5em;
خب وقتی گفتی slot='start' اینم بکن margin-start

2022-11-25 15:51 UTC, AliMD commented on pwa/src/component/job-item.ts
> +            ${this.__renderDescription('بر عمر کار کشته لعنت')}
بیش باد 😆

2022-11-25 15:51 UTC, AliMD commented on pwa/src/component/page-flight-finder.ts
> +        margin: 1em 1em !important;
چرا important؟!

2022-11-25 15:51 UTC, AliMD commented on pwa/src/component/page-flight-finder.ts
>          padding: 0 !important;
important ؟!

2022-11-25 18:37 UTC, AliMD commented on pwa/src/component/job-item.ts
> +            ${this.__renderDescription('بر عمر کار کشته لعنت')}
بله حتماً
اضافه کن همه رو

2022-11-25 18:39 UTC, AliMD approved these changes

2022-11-25 18:39 UTC, AliMD commented on pwa/src/director/job-add.ts
> +  jobListSignal.request({});
تایپ request این چرا اینجوریه ؟! باید void باشه

2022-11-27 11:19 UTC, merged

2022-11-29 07:35 UTC, njfamirm commented on pwa/src/component/job-item.ts
> +            ${this.__renderDescription('بر عمر کار کشته لعنت')}
Ok