fix(api): handle preflight request
AliMD/flight-finder pull request #26
Opened 2022-11-24 20:59 UTC by njfamirm

2022-11-25 15:31 UTC, AliMD commented on pwa/src/director/job-add.ts
> +      url: window.appConfig?.api + '/job' ?? '/job',
اینکه ؟؟ دیگه کار نمیکنه!
میشه undefined/job

2022-11-25 15:34 UTC, AliMD requested changes

2022-11-25 15:34 UTC, AliMD commented on telegram-notifier/src/lib/bot.ts
> +process.once('SIGINT', () => bot.stop('SIGINT'));
این چیه؟!
واقعا لازمه؟
خودش نمیگیره همچین سیگنالی رو
از طرفی کلا بات که دیتایی نداره چه اهمیتی داره درست stop شدنش؟

2022-11-25 15:36 UTC, AliMD requested changes

2022-11-25 15:36 UTC, AliMD commented on api/src/route/options.ts
> +  connection.reply({
اوه!
این چیه

2022-11-25 15:36 UTC, AliMD commented on api/src/route/options.ts
> +  connection.serverResponse.setHeader('Access-Control-Allow-Origin', '*');
این خب میرفت تو nano-server دیگه
از طرفی مگه چیکار کردیم که simple request نمیزنه؟
تازه localhost که همیشه استثنا بود!

2022-11-25 15:37 UTC, njfamirm commented on telegram-notifier/src/lib/bot.ts
> +process.once('SIGINT', () => bot.stop('SIGINT'));
اوکی

2022-11-25 18:42 UTC, AliMD commented
چون از storage client قدیم داره استفاده می‌کنه
اگر به alwatr next لینکس کنی درست میشه
yarn link

2022-11-26 09:43 UTC, njfamirm commented on api/src/route/options.ts
> +  connection.serverResponse.setHeader('Access-Control-Allow-Origin', '*');
من که دوباره خوندم فهمیدم simple request فقط برای این بود که preflight نزنه
که البته ریکوئست ما هم simple نیست

2022-11-26 10:23 UTC, njfamirm commented
https://github.com/AliMD/alwatr/pull/43۳

2022-11-29 12:34 UTC, merged