chore: build configurations
AliMD/flight-finder pull request #53
Opened 2022-12-03 13:05 UTC by MM25Zamanian

2022-12-04 09:55 UTC, AliMD commented on .vscode/settings.json
>      "*/src/**/*.map": true,
اینا کلی بشه بهتر نیست؟

2022-12-04 11:06 UTC, AliMD requested changes

2022-12-04 11:06 UTC, AliMD commented on telegram-notifier/package.json
> +    "npm": ">=8.0.0"
یارن

2022-12-04 11:06 UTC, AliMD commented on telegram-notifier/tsconfig.json
> +      "DOM.Iterable"
!

2022-12-04 13:00 UTC, AliMD commented
> @AliMD من ارور ورک فلو هارو متوجه نمیشم

به نظرم یک بار y l  میزدی متوجه میشدی

<img width="1230" alt="Screen Shot 2022-12-04 at 4 28 26 PM" src="https://user-images.githubusercontent.com/697913/205491909-bb183bb0-2f76-42c5-b7ab-37a196ae88e1.png">

2022-12-04 14:10 UTC, AliMD commented on api/tsconfig.json
> +    "composite": true,
اینم باید فالس باشه

2022-12-04 14:23 UTC, AliMD commented on .vscode/settings.json
> +    ".map": true,
اینجوری که کار نمیکنه برای من!

2022-12-04 15:13 UTC, AliMD commented on api/tsconfig.json
> +    "outDir": "./src",
این چرا اینجوریه باز 😢

2022-12-05 13:03 UTC, AliMD commented on api/tsconfig.json
> +    "outDir": "./src",
@MM25Zamanian @njfamirm 
من نرسیدم به این کارهای دیگه‌ای پیش اومد

2022-12-05 13:30 UTC, AliMD commented on api/tsconfig.json
> +      "DOM.Iterable"
بدون Iterable که خطا نمیده!
دام باشه ولی Iterable رو بردار

2022-12-05 13:31 UTC, AliMD commented on pwa/index.html
> +    <link rel="apple-touch-icon" href="/image/apple-touch-icon.png" />
این / های اول نباید باشه 😭

2022-12-05 13:32 UTC, AliMD commented on telegram-notifier/tsconfig.json
> +      "DOM.Iterable"
.

2022-12-05 13:32 UTC, AliMD commented on telegram-notifier/tsconfig.json
> +    "outDir": "./src",
.

2022-12-05 14:18 UTC, njfamirm commented on telegram-notifier/tsconfig.json
> +    "outDir": "./src",
این چی باید بشه؟
در جریان نیستم

بگین که سریع مرج کنم استارتر بسازم

2022-12-05 14:25 UTC, njfamirm commented on api/tsconfig.json
> +    "outDir": "./src",
روت باید باشه؟؟

2022-12-06 11:55 UTC, merged